### ISSUE TITLE
Select All functionality.

### ISSUE THREAD

**Issue by ryanhca** [insin/react-filtered-multiselect#10]
Just wondering if anyone had implemented a "Select All" functionality to the component. I don't want to use jQuery like I'm doing now, because I'd need to have a unique "Id" attached to each <select> tag. That seems more involved and clunky. Any good "React-esque" solutions out there to turn the option.selected = true on the click of a button?

**Comment by insin** [comment]
The `FilteredMultiSelect` component doesn't hold the state for selected options - you do, so you'd effectively implement Select All by passing all the options as the `selectedOptions` prop.

e.g. in the demo's [`BasicSelection` component](https://github.com/insin/react-filtered-multiselect/blob/f90a228b60091b66b743eefc97caa8c73dec890b/demo/src/index.js#L17) Clear Selection is implemented as `this.setState({selectedOptions: []})` and Select All could be implemented as `this.setState({selectedOptions: CULTURE_SHIPS})`.

You could consider Select All a separate option to using this component at all - if the user wants to select all the available items they no longer need a way to filter them down to the ones they're interested in.
