### ISSUE TITLE
Deprecated class creation

### ISSUE THREAD

**Issue by jarekwg** [insin/react-filtered-multiselect#11]
`React.createClass` is deprecated

Should be using `class FilteredMultiSelect extends React.Component {` instead.

I'm happy to submit a PR if this package is still being maintained. @insin you around?

**Comment by insin** [comment]
Sure

Wow it looks like this used the first ever version of nwb and it has `*` as the version number, so building it will be more work than the PR 😹

**Comment by insin** [comment]
Released in v0.5.0

**Comment by jarekwg** [comment]
Awesome, thanks for the prompt update! :)
