### ISSUE TITLE
Question on Options

### ISSUE THREAD

**Issue by srconklin** [insin/react-filtered-multiselect#3]
This is really a nice component... 
I have not been able to find a really robust filterable single select box.
Can this component be configured to turn off multi-select portion (and maybe size it to 1) so that it becomes a single select box with the filter functionality only?

**Comment by insin** [comment]
Here's a quick tweak which lets you specify multiple={false} and hides the `<button>`:in that case:

http://bl.ocks.org/insin/985c434f8bf736dc45a1

It just doesn't seem as useful as something like [react-select](http://jedwatson.github.io/react-select/).

**Comment by srconklin** [comment]
wow! thanks for that.. very nice
