### ISSUE TITLE
Fix getDOMNode() warning in React 0.14

### ISSUE THREAD

**Issue by lemniscate613** [insin/react-filtered-multiselect#5]
This line gives an error in React 0.14: https://github.com/insin/react-filtered-multiselect/blob/master/dist/react-filtered-multiselect.js#L165

You can now access DOM nodes directly without getDOMNode(): https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html#dom-node-refs

**Comment by insin** [comment]
Fixed in v0.4.0, thanks for the report!

**Comment by lemniscate613** [comment]
Thank you!
